In [1]:
# câu 1 : import module numpy và in ra version

import numpy as np

print(np.__version__)

1.26.4


In [2]:
# câu 2 : Tạo mảng 1 chiều từ 0 đến 9

import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np
b = np.ones((3,3), dtype=bool)
print(b)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
# câu 4 : Lấy những phần tử mà thoả mãn một điều kiện cho trước của mảng một chiều

import numpy as np

# tạo mảng một chiều từ 0 đến 9
arr = np.arange(0,10)
print(arr)

# # Tìm phần tử có giá trị lẻ
# arr_odd =
x = arr[arr % 2 == 1]
print(x)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [5]:
# câu 5 : Thay thế phần tử thoả mãn điều kiện cho trước bằng 1 một giá trị khác

import numpy as np

# tạo mảng một chiều từ 0 đến 9
arr = np.arange(0,10)
print(arr)
# # Thay thế phần tử có giá trị lẻ bằng -1
x = np.where(arr % 2 == 1, -1, arr)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [6]:
# câu 6 : Thay thế phần tử thoả mãn điều kiện cho trước bằng 1 một giá khác
# nhưng không thay đổi mảng ban đầu
import numpy as np
arr = np.arange(0,10)
print('before:' ,arr)
# Thay thế tất cả số lẻ bằng giá trị -1 nhưng mảng ban đầu không thay đổi
x = np.where(arr % 2 == 1, -1, arr)
print('after:', arr)
print('out:' ,x)

before: [0 1 2 3 4 5 6 7 8 9]
after: [0 1 2 3 4 5 6 7 8 9]
out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [7]:
# câu 7 : Định dạng/chuyển mảng

# Chuyển mảng 1 chiều thành mảng 2 chiều có 2 hàng ( dòng )

import numpy as np

# tạo mảng 1d gồm 10 phần tử
arr = np.arange(10)
print(arr)

# mảng 2 chiều có 2 hàng
arr_2d=arr.reshape(2,-1)
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
# câu 8:  xếp chồng 2 mảng theo chiều dọc
import numpy as np

# Tạo mảng hai chiều (2 hàng 5 cột) từ 0 đến 9
arr1 = np.arange(10).reshape(2, -1)
print('arr1: \n', arr1)

# Tạo mảng hai chiều (2 hàng 5 cột) chỉ có giá trị 1
arr2 = np.repeat(1, 10).reshape(2, -1)
print('arr2: \n', arr2)

# Cách 1: Dùng np.vstack() để xếp chồng theo chiều dọc
c = np.vstack((arr1, arr2))
print("Cách 1: \n", c)

# Cách 2: Dùng np.concatenate() với axis=0
d = np.concatenate((arr1, arr2), axis=0)
print("Cách 2: \n", d)

# Cách 3: Dùng np.row_stack() để xếp chồng theo chiều dọc
e = np.row_stack((arr1, arr2))
print("Cách 3: \n", e)


arr1: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr2: 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
Cách 1: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Cách 2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Cách 3: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
# câu 9 : xếp chồng 2 mảng theo chiều ngang
import numpy as np

# Tạo mảng hai chiều (2 hàng 5 cột) từ 0 đến 9
arr1 = np.arange(10).reshape(2, -1)
print('arr1: \n', arr1)

# Tạo mảng hai chiều (2 hàng 5 cột) chỉ có giá trị 1
arr2 = np.repeat(1, 10).reshape(2, -1)
print('arr2: \n', arr2)

# Cách 1: Dùng np.hstack() để xếp chồng theo chiều ngang
c = np.hstack((arr1, arr2))
print("Cách 1: \n", c)

# Cách 2: Dùng np.concatenate() với axis=1
d = np.concatenate((arr1, arr2), axis=1)
print("Cách 2: \n", d)

# Cách 3: Dùng np.column_stack() để xếp chồng theo chiều ngang
e = np.column_stack((arr1, arr2))
print("Cách 3: \n", e)


arr1: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr2: 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
Cách 1: 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Cách 2: 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Cách 3: 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [15]:
# câu 10
import numpy as np

# Chỉ dùng hàm numpy có sẵn với mảng arr như bên dưới
arr = np.array([1, 2, 3])
print("arr: ", arr)

# Tạo mảng mới lặp lại mỗi phần tử trong arr 3 lần
arr_repeat_elements = np.repeat(arr, 3)
print(arr_repeat_elements)

# Tạo mảng mới lặp lại mảng arr 3 lần
arr_repeat_array = np.tile(arr, 3)
print(arr_repeat_array)


arr:  [1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [17]:
# câu 11: Lấy phần tử chung của 2 mảng a và b
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Lấy phần tử chung của 2 mảng a và b
common_elements = np.intersect1d(a, b)
print(common_elements)


[2 4]


In [19]:
# câu 12 : Xoá phần tử từ 1 mảng mà tồn tại trong 1 mảng khác
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# Từ mảng a, xóa tất cả các phần tử ở a mà đã có trong mảng b
result = np.setdiff1d(a, b)
print(result)


[1 2 3 4]


In [21]:
# Câu 13
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Lấy tất cả vị trí nơi giá trị các phần tử của 2 mảng a, b giống nhau
matching_indices = np.where(a == b)[0]
print(matching_indices)


[1 3 5 7]


In [22]:
# câu 14 : Lấy tất cả các giá trị trong 1 phạm vi cho trước từ 1 mảng
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])

# Tìm tất cả vị trí của các phần tử có giá trị trong phạm vi [5,10]

# Cách 1: Dùng np.where() để lấy chỉ số các phần tử trong phạm vi [5, 10]
index = np.where((a >= 5) & (a <= 10))
print("Cách 1: \n", a[index])

# Cách 2: Dùng np.nonzero() để lấy chỉ số các phần tử trong phạm vi [5, 10]
index = (a >= 5) & (a <= 10)
print("Cách 2: \n", a[index])

# Cách 3: Trực tiếp lấy kết quả các phần tử trong phạm vi [5, 10]
result = a[(a >= 5) & (a <= 10)]
print("Cách 3: \n", result)


Cách 1: 
 [ 6  9 10]
Cách 2: 
 [ 6  9 10]
Cách 3: 
 [ 6  9 10]


In [23]:
# Câu 15
import numpy as np

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Dùng hàm maximum để lấy giá trị lớn hơn giữa a và b
result_maximum = np.maximum(a, b)
print("Dùng maximum: ", result_maximum)

# Dùng hàm where để lấy giá trị lớn hơn giữa a và b
result_where = np.where(a > b, a, b)
print("Dùng where:    ", result_where)


Dùng maximum:  [6 7 9 8 9 7 5]
Dùng where:     [6 7 9 8 9 7 5]


In [25]:
# câu 16 : Hoán các cột trong mảng 2 chiều

import numpy as np

# Cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3, 3)
print(arr)

# Hoán cột có index 0 và index 1 trong mảng arr
arr[:, [0, 1]] = arr[:, [1, 0]]
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [26]:
# câu 17 :  Hoán 2 hàng trong mảng 2 chiều

import numpy as np

# Cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3, 3)
print("Mảng ban đầu:\n", arr)

# Hoán dòng có index 0 và index 1 trong mảng arr
arr[[0, 1]] = arr[[1, 0]]
print("Mảng sau khi hoán đổi dòng 0 và dòng 1:\n", arr)


Mảng ban đầu:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Mảng sau khi hoán đổi dòng 0 và dòng 1:
 [[3 4 5]
 [0 1 2]
 [6 7 8]]


In [27]:
# câu 18 :

import numpy as np

# Cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3, 3)
print(arr)

# Đảo ngược hàng (dòng) trong mảng 2 chiều
arr_reversed_rows = arr[::-1]
print(arr_reversed_rows)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [28]:
# Câu 19
import numpy as np

# Cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3, 3)
print(arr)

# Đảo ngược cột trong mảng 2 chiều
arr_reversed_columns = arr[:, ::-1]
print(arr_reversed_columns)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [29]:
# Câu 20 :  Tạo mảng 2 chiều chứa số random kiểu float từ 5 đến 10
import numpy as np

# Tạo mảng 2 chiều 5x3 từ 5 đến 10
arr = np.random.uniform(5, 10, size=(5, 3))
print(arr)


[[7.28634214 9.90180124 5.16399965]
 [8.34178018 7.7757268  6.42229118]
 [6.15475717 6.57902399 5.81621201]
 [5.26843152 9.59666461 8.11187017]
 [5.72835205 6.55504738 7.23340188]]


In [30]:
# Câu 21
import numpy as np

# Cho mảng a chứa các số ngẫu nhiên từ [1, 50)
a = np.random.randint(1, 50, size=10)  # Ví dụ mảng a có 10 phần tử ngẫu nhiên từ 1 đến 50
print("Mảng a:\n", a)

# Cách 1: Dùng hàm np.clip để thay thế giá trị lớn hơn 30 thành 30 và dưới 10 thành 10
result = np.clip(a, 10, 30)
print("Cách 1: \n", result)

# Cách 2: Dùng hàm np.where để thay thế giá trị lớn hơn 30 thành 30 và dưới 10 thành 10
result = np.where(a > 30, 30, np.where(a < 10, 10, a))
print("Cách 2: \n", result)


Mảng a:
 [40  1 29 18 10 30  9 48 44 35]
Cách 1: 
 [30 10 29 18 10 30 10 30 30 30]
Cách 2: 
 [30 10 29 18 10 30 10 30 30 30]


In [31]:
# câu 22: Lấy vị trí của n giá trị đứng đầu từ một mảng numpy

import numpy as np

# Cho mảng a chứa các số ngẫu nhiên từ [1, 50)
a = np.random.randint(1, 50, size=10)
print("Mảng a:\n", a)

# Lấy vị trí của 5 giá trị lớn nhất trong một mảng a

# Cách 1: Dùng hàm np.argsort()
print("Cách 1:")
# Lấy vị trí của các phần tử lớn nhất
indices_sorted = np.argsort(a)[-5:]  # Lấy 5 chỉ số cuối cùng trong mảng đã sắp xếp
values_sorted = a[indices_sorted]    # Lấy giá trị tương ứng từ mảng a
print('Vị trí: ', indices_sorted)
print('Giá trị: ', values_sorted)

# Cách 2: Dùng hàm np.argpartition()
print("Cách 2:")
# Lấy vị trí của các phần tử lớn nhất bằng np.argpartition
indices_partition = np.argpartition(a, -5)[-5:]  # Lấy 5 chỉ số lớn nhất
values_partition = a[indices_partition]          # Lấy giá trị tương ứng từ mảng a
print('Vị trí: ', indices_partition)
print('Giá trị: ', values_partition)


Mảng a:
 [45  3  4 24 49 31 37 26 27 29]
Cách 1:
Vị trí:  [9 5 6 0 4]
Giá trị:  [29 31 37 45 49]
Cách 2:
Vị trí:  [9 6 5 0 4]
Giá trị:  [29 37 31 45 49]


In [32]:
# câu 23: Chuyển đổi một mảng chứa nhiều mảng thành một mảng 1d phẳng
import numpy as np

# Cho array_of_arrays như sau
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3], dtype=object)
print('array_of_arrays: ', array_of_arrays)

# Cách 1: Dùng np.concatenate() để chuyển đổi thành mảng 1D phẳng
arr_2d = np.concatenate(array_of_arrays)
print("Cách 1: \n", arr_2d)

# Cách 2: Dùng np.flatten() hoặc np.ravel() để chuyển đổi thành mảng 1D phẳng
arr_2d = array_of_arrays.flatten()
print("Cách 2: \n", arr_2d)

# Cách 3: Dùng np.hstack() để chuyển đổi thành mảng 1D phẳng
arr_2d = np.hstack(array_of_arrays)
print("Cách 3: \n", arr_2d)



array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
Cách 1: 
 [0 1 2 3 4 5 6 7 8 9]
Cách 2: 
 [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
Cách 3: 
 [0 1 2 3 4 5 6 7 8 9]


In [35]:
# câu 24: Tìm giá trị lớn nhất trong mỗi hàng của mảng 2d
import numpy as np

# Cho mảng a
a = np.random.randint(1, 10, [5, 3])
print(a)

# Cách 1: Dùng np.amax để tìm giá trị lớn nhất trong mỗi hàng
result = np.amax(a, axis=1)
print("Cách 1: ", result)

# Cách 2: Dùng np.apply_along_axis và np.max để tìm giá trị lớn nhất trong mỗi hàng
result = np.apply_along_axis(np.max, axis=1, arr=a)
print("Cách 2: ", result)


[[7 7 8]
 [5 8 1]
 [8 2 9]
 [6 4 6]
 [3 3 9]]
Cách 1:  [8 8 9 6 9]
Cách 2:  [8 8 9 6 9]


In [37]:
# Câu 25
import numpy as np

# Cho mảng a
a = np.random.randint(1, 10, [5, 3])
print(a)

# Tính tỷ số min/max cho mỗi hàng trong mảng a
min_values = np.min(a, axis=1)
max_values = np.max(a, axis=1)
ratio_min_max = min_values / max_values
print('min-by-max:', ratio_min_max)


[[5 8 6]
 [2 7 3]
 [6 8 3]
 [9 5 3]
 [8 1 4]]
min-by-max: [0.625      0.28571429 0.375      0.33333333 0.125     ]


In [38]:
# câu 26: Tìm các vị trí có giá trị trùng lặp trong một mảng numpy

import numpy as np

# Cho mảng a
a = np.random.randint(0, 5, 10)
print(a)

# Tạo mảng out gồm tất cả giá trị là True
out = np.full(a.shape, True)

# Tìm tất cả các giá trị duy nhất và chỉ số lần đầu tiên xuất hiện
unique_a, return_index = np.unique(a, return_index=True)

# Đánh dấu các chỉ số lần đầu tiên xuất hiện là False
out[return_index] = False

# In ra kết quả
print(out)


[2 3 1 3 2 4 1 3 4 2]
[False False False  True  True False  True  True  True  True]


In [39]:
# câu 27: loại bỏ tất cả các giá trị còn thiếu (np.nan) trong một mảng

import numpy as np

# Cho mảng a
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
print(a)

# Bỏ tất cả các giá trị nan từ mảng a
out = a[~np.isnan(a)]
print(out)


[ 1.  2.  3. nan  5.  6.  7. nan]
[1. 2. 3. 5. 6. 7.]


In [40]:
# Câu 28
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

# Tính khoảng cách giữa hai mảng a và b
dist = np.linalg.norm(a - b)
print(dist)


6.708203932499369


In [41]:
# câu 29: Tìm tất cả các cực đại cục bộ (hay còn gọi các đỉnh) trong một mảng 1d
import numpy as np

# Cho mảng a
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# Tính sự thay đổi giữa các phần tử liên tiếp
doublediff = np.diff(np.sign(np.diff(a)))

# Tìm các cực đại (đỉnh) là các điểm có sự thay đổi từ dương sang âm
peak_locations = np.where(doublediff == -2)[0] + 1  # +1 để điều chỉnh vị trí vì np.diff giảm chiều dài mảng

print(peak_locations)


[2 5]
